/**
 * This file is autogenerated by AssetChain_Starterkits.(inspired by scaffold-eth)

 * @author ASSETCHAIN DEVREL TEAM
 *  @author James Harrison(https://github.com/KodeSage/)
 *  @author  Okorie Ebube(https://github.com/theiceeman)

 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  assetchain_testnet: {
    contractName: "Greeter",
    chainId: "42421",
    address: "0x1Cb2a1d9a592Ed386C3126a5cabF4C7A10fD9406",
    abi: [
      {
        inputs: [
          {
            internalType: "string",
            name: "_greeting",
            type: "string",
          },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
      },
      {
        inputs: [],
        name: "greet",
        outputs: [
          {
            internalType: "string",
            name: "",
            type: "string",
          },
        ],
        stateMutability: "view",
        type: "function",
      },
      {
        inputs: [
          {
            internalType: "string",
            name: "_greeting",
            type: "string",
          },
        ],
        name: "setGreeting",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
      },
    ],
    inheritedFunctions: {},
  },
};

export default deployedContracts;
